const mongoose = require('mongoose');

const Matchlive = new mongoose.Schema({
    sport_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Sport', default: null },
    source_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Source', default: null },
    match_id: { type: Number,  unique: true },
    title: { type: string },
    short_title: { type: string },
    subtitle: { type: string },
    match_number: { type: string },
    format: { type: number },
    format_str: { type: string },
    status: { type: number },
    status_str: { type: string },
    status_note: { type: string },
    verified: { type: string },
    pre_squad: { type: string },
    odds_available: { type: string },
    game_state: { type: number },
    game_state_str: { type: string },
    competition: {
      cid: { type: Number },
      title:  { type: String },
      abbr:  { type: String },
      type:  { type: String },
      category:  { type: String },
      match_format:  { type: String },
      season:  { type: String },
      status:  { type: String },
      datestart:  { type: String },
      dateend:  { type: String },
      country:  { type: String },
      total_matches:  { type: String },
      total_rounds:  { type: String },
      total_teams:  { type: String },
    },
    teama: {
      team_id: { type: Number },
      name: { type: String },
      short_name: { type: String },
      logo_url: { type: String },
      thumb_url: { type: String },
      scores_full: { type: String },
      scores: { type: String },
      overs: { type: String },
    },
    teamb: {
      team_id: { type: Number },
      name: { type: String },
      short_name: { type: String },
      logo_url: { type: String },
      thumb_url: { type: String },
      scores_full: { type: String },
      scores: { type: String },
      overs: { type: String },
    },
    date_start: { type: string },
    date_end: { type: string },
    timestamp_start: { type: number },
    timestamp_end: { type: number },
    date_start_ist: { type: string },
    date_end_ist: { type: string },
    venue: {
      venue_id: { type: String },
      name: { type: String },
      location: { type: String },
      country: { type: String },
      timezone: { type: String },
    },
    umpires: { type: string },
    referee: { type: string },
    equation: { type: string },
    live: { type: string },
    result: { type: string },
    result_type: { type: number },
    win_margin: { type: string },
    winning_team_id: { type: number },
    commentary: { type: number },
    wagon: { type: number },
    latest_inning_number: { type: number },
    presquad_time: { type: string },
    verify_time: { type: string },
    match_dls_affected: { type: string },
    live_inning_number: { type: number },
    day: { type: string },
    session: { type: string },
    weather: {
      weather: { type: string },
      weather_desc: { type: string },
      temp: { type: number },
      humidity: { type: number },
      visibility: { type: number },
      wind_speed: { type: string },
      clouds: { type: number },
    },
    pitch: {
      pitch_condition: { type: string },
      batting_condition: { type: string },
      pace_bowling_condition: { type: string },
      spine_bowling_condition: { type: string },
    },
    toss: {
      text: { type: String },
      winner: { type: Number },
      decision: { type: Number },
    },
    points: {
      teama: {
        playing11: {type : [{
          pid: { type: string },
          name: { type: string },
          role: { type: string },
          rating: { type: string },
          point: { type: string },
          starting11: { type: string },
          run: { type: string },
          four: { type: string },
          six: { type: string },
          sr: { type: string },
          fifty: { type: string },
          duck: { type: string },
          wkts: { type: string },
          maidenover: { type: string },
          er: { type: string },
          catch: { type: string },
          runoutstumping: { type: string },
          runoutthrower: { type: string },
          runoutcatcher: { type: string },
          directrunout: { type: string },
          stumping: { type: string },
          thirty: { type: string },
          bonus: { type: string },
          bonuscatch: { type: string },
          bonusbowedlbw: { type: string },
        }]},
        substitute: {type : [{
          pid: { type: string },
          name: { type: string },
          role: { type: string },
          rating: { type: string },
          point: { type: string },
          starting11: { type: string },
          run: { type: string },
          four: { type: string },
          six: { type: string },
          sr: { type: string },
          fifty: { type: string },
          duck: { type: string },
          wkts: { type: string },
          maidenover: { type: string },
          er: { type: string },
          catch: { type: string },
          runoutstumping: { type: string },
          runoutthrower: { type: string },
          runoutcatcher: { type: string },
          directrunout: { type: string },
          stumping: { type: string },
          thirty: { type: string },
          bonus: { type: string },
          bonuscatch: { type: string },
          bonusbowedlbw: { type: string },
        }]},
      },
      teamb: {
        playing11: {type : [{
          pid: { type: string },
          name: { type: string },
          role: { type: string },
          rating: { type: string },
          point: { type: string },
          starting11: { type: string },
          run: { type: string },
          four: { type: string },
          six: { type: string },
          sr: { type: string },
          fifty: { type: string },
          duck: { type: string },
          wkts: { type: string },
          maidenover: { type: string },
          er: { type: string },
          catch: { type: string },
          runoutstumping: { type: string },
          runoutthrower: { type: string },
          runoutcatcher: { type: string },
          directrunout: { type: string },
          stumping: { type: string },
          thirty: { type: string },
          bonus: { type: string },
          bonuscatch: { type: string },
          bonusbowedlbw: { type: string },
        }]},
        substitute: {type : [{
          pid: { type: string },
          name: { type: string },
          role: { type: string },
          rating: { type: string },
          point: { type: string },
          starting11: { type: string },
          run: { type: string },
          four: { type: string },
          six: { type: string },
          sr: { type: string },
          fifty: { type: string },
          duck: { type: string },
          wkts: { type: string },
          maidenover: { type: string },
          er: { type: string },
          catch: { type: string },
          runoutstumping: { type: string },
          runoutthrower: { type: string },
          runoutcatcher: { type: string },
          directrunout: { type: string },
          stumping: { type: string },
          thirty: { type: string },
          bonus: { type: string },
          bonuscatch: { type: string },
          bonusbowedlbw: { type: string },
        }]},
      },
    },
  });

module.exports = mongoose.model('Matchlive', Matchlive);