const mongoose = require('mongoose');

const RankingSchema = new mongoose.Schema({
    sport_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Sport', required: true },
    source_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Source', required: true },
    ranks: {
        batsmen: {
            odis: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            tests: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
        },
        bowlers: {
            odis: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            tests: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
        },
        'all-rounders': {
            odis: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            tests: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
        },
        teams: {
            odis: {type : [{
                rank: { type: String },
                tid: { type: String },
                team: { type: String },
                points: { type: String },
                rating: { type: String },
                logo_url: { type: String },
                matches: { type: String },
            }]},
            tests: {type : [{
                rank: { type: String },
                tid: { type: String },
                team: { type: String },
                points: { type: String },
                rating: { type: String },
                logo_url: { type: String },
                matches: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                tid: { type: String },
                team: { type: String },
                points: { type: String },
                rating: { type: String },
                logo_url: { type: String },
                matches: { type: String },
            }]},
        },
    },
    women_ranks: {
        batsmen: {
            odis: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
        },
        bowlers: {
            odis: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
        },
        'all-rounders': {
            odis: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                pid: { type: String },
                player: { type: String },
                team: { type: String },
                rating: { type: String },
                careerbestrating: { type: String },
            }]},
        },
        teams: {
            odis: {type : [{
                rank: { type: String },
                tid: { type: String },
                team: { type: String },
                points: { type: String },
                rating: { type: String },
                logo_url: { type: String },
                matches: { type: String },
            }]},
            t20s: {type : [{
                rank: { type: String },
                tid: { type: String },
                team: { type: String },
                points: { type: String },
                rating: { type: String },
                logo_url: { type: String },
                matches: { type: String },
            }]},
        },
    },
    groups: {
        teams: { type: String },
        batsmen: { type: String },
        bowlers: { type: String },
        'all-rounders': { type: String },
    },
    formats: {
        tests: { type: String },
        odis: { type: String },
        t20s: { type: String },
    },
    test_championship_ranking: {type : [{
        team_id: { type: String },
        team_name: { type: String },
        rank: { type: String },
        qualified: { type: String },
        total_match: { type: String },
        win: { type: String },
        loss: { type: String },
        drawn: { type: String },
        noresult: { type: String },
        points: { type: String },
        home_win: { type: String },
        away_win: { type: String },
        pct: { type: String },
    }]},
});

module.exports = mongoose.model('Ranking', RankingSchema);